// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: DASH_UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_uiRegenPanel;
lv_obj_t *ui_RegenText;
lv_obj_t *ui_uiSoCPanel;
lv_obj_t *ui_BarSoC;
lv_obj_t *ui_SoCText;
lv_obj_t *ui_SoCNumerical;
lv_obj_t *ui_BarTemp;
lv_obj_t *ui_tempText;
lv_obj_t *ui_tempNumerical;
lv_obj_t *ui_hvState;
lv_obj_t *ui_speedNumerical;
lv_obj_t *ui_speedText;
lv_obj_t *ui_tsalText;
lv_obj_t *ui_BMStateNumerical;
lv_obj_t *ui_BMSText;
lv_obj_t *ui_ButtonCoolPump;
lv_obj_t *ui_CoolPumpText;
lv_obj_t *ui_ButtonRADFan;
lv_obj_t *ui_ButtonAccFan;
lv_obj_t *ui_ButtonRTD;
lv_obj_t *ui_RadFanText;
lv_obj_t *ui_AccFanText;
lv_obj_t *ui_RTDText;
lv_obj_t *ui_ButtonDataLog;
lv_obj_t *ui_DataLogText;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
