// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: DASH_UI

#ifndef _DASH_UI_UI_H
#define _DASH_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_uiRegenPanel;
extern lv_obj_t *ui_RegenText;
extern lv_obj_t *ui_uiSoCPanel;
extern lv_obj_t *ui_BarSoC;
extern lv_obj_t *ui_SoCText;
extern lv_obj_t *ui_SoCNumerical;
extern lv_obj_t *ui_BarTemp;
extern lv_obj_t *ui_tempText;
extern lv_obj_t *ui_tempNumerical;
extern lv_obj_t *ui_hvState;
extern lv_obj_t *ui_speedNumerical;
extern lv_obj_t *ui_speedText;
extern lv_obj_t *ui_tsalText;
extern lv_obj_t *ui_BMStateNumerical;
extern lv_obj_t *ui_BMSText;
extern lv_obj_t *ui_ButtonCoolPump;
extern lv_obj_t *ui_CoolPumpText;
extern lv_obj_t *ui_ButtonRADFan;
extern lv_obj_t *ui_ButtonAccFan;
extern lv_obj_t *ui_ButtonRTD;
extern lv_obj_t *ui_RadFanText;
extern lv_obj_t *ui_AccFanText;
extern lv_obj_t *ui_RTDText;
extern lv_obj_t *ui_ButtonDataLog;
extern lv_obj_t *ui_DataLogText;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// FONTS
LV_FONT_DECLARE( ui_font_Font1);
LV_FONT_DECLARE( ui_font_Font_3);
LV_FONT_DECLARE( ui_font_OrbitronBold15);
LV_FONT_DECLARE( ui_font_OrbitronBold25);
LV_FONT_DECLARE( ui_font_OrbitronBold40);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
